language: node_js

os:
  - "linux"
  - "osx"

node_js:
  - node
  - 4
  - 5
  - 6
  - iojs

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - elasticsearch
  - rabbitmq

before_install:
  - "export NODE_ENV=test"
  - "npm config set strict-ssl false"
  - "npm install -g chai istanbul jsdoc mocha babel-register"

before_script:
  - "sleep 10"

install:
    - ./.travis/install.sh
    - npm install
    - ./bin/microcrawler config init

