language: node_js

os:
  - "linux"
  - "osx"

node_js:
  - 4
  - 5
  - 6
  - iojs

services:
  - elasticsearch
  - rabbitmq

before_install:
  - "export NODE_ENV=test"
  - "npm config set strict-ssl false"
  - "npm install -g chai istanbul jsdoc mocha babel-register"

before_script:
  - "sleep 10"

install:
    - ./.travis/install.sh
    - npm install
    - ./bin/microcrawler config init

